# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.26.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
z = np.zeros(10,int)
print(z.itemsize)

4


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPyth

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
z = np.arange(10,49,2)
print(z)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
# z = np.arange(10,49,2)
# print(z)
# for i in range(len(z)):
#   z[i] = z[len(z)-i-1]
# print(z)
# my method
z = np.arange(10,49,2)
print(z)
z=z[::-1]# short method
print(z)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
m = np.arange(9).reshape(3,3)
print(m)
p = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(p)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [2 3 4]
 [4 5 6]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
# p = [1,2,0,0,4,0,]
# ind = []
# for i in range(len(p)):
#   if(p[i]!=0):
#     ind.append(i)
# print(ind)
# my solution

nz = np.nonzero([1,2,0,0,4,0])
print(nz)



(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3,3))# or we can do it by generating randomvalues and appending them in a 3*3*3 list

array([[[0.20407775, 0.56270964, 0.45397195],
        [0.95410579, 0.46891128, 0.28358301],
        [0.42126299, 0.13418398, 0.32662701]],

       [[0.36410672, 0.41298347, 0.19222403],
        [0.32710262, 0.75108563, 0.22449564],
        [0.03836288, 0.71510692, 0.84133424]],

       [[0.38535582, 0.76520638, 0.81435545],
        [0.27046027, 0.48932807, 0.27233005],
        [0.2130683 , 0.82987081, 0.95670294]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
u = np.random.random((10,10))
print(u)
print(u.max())
print(u.min())

[[0.24689891 0.787635   0.90844153 0.39138193 0.25107298 0.51226462
  0.92313128 0.23513344 0.35222552 0.80479068]
 [0.86802722 0.70859413 0.69507691 0.02828704 0.07759343 0.54121566
  0.96208318 0.94034851 0.85858869 0.96864938]
 [0.1696241  0.26845449 0.76367441 0.52173748 0.7584712  0.3347992
  0.6355081  0.89742631 0.62412106 0.26243893]
 [0.11920662 0.76034195 0.66723608 0.79870639 0.92442224 0.02800726
  0.53373369 0.33622542 0.12658792 0.54494142]
 [0.62449836 0.89796992 0.88234198 0.92049404 0.20314668 0.48375381
  0.87159042 0.0020586  0.75914012 0.30372894]
 [0.49619542 0.5769406  0.02614202 0.9613491  0.45594277 0.74194401
  0.79489095 0.96863778 0.51367814 0.5632959 ]
 [0.58442975 0.3880986  0.31512904 0.90605208 0.79917435 0.67922281
  0.82954912 0.95073007 0.80584086 0.89860059]
 [0.90463327 0.58559706 0.64977816 0.99065612 0.50755401 0.87494513
  0.38657454 0.92021834 0.98394025 0.07446331]
 [0.04799589 0.37125663 0.81523784 0.21898861 0.9143161  0.63155024
  0.14212015 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [53]:
z = np.random.random((1,30))
print(z)
print(z.mean())
# sum = 0
# p = z[0]
# for i in range(len(p)):
#   sum += p[i]
# mean = sum/len(p)
# print(mean)

# this is my code for this above function 

[[0.02454389 0.07898602 0.83640216 0.31927935 0.52571161 0.90707051
  0.68044757 0.77244165 0.20573631 0.41025614 0.22022171 0.18440855
  0.80200173 0.29390606 0.11491921 0.77322126 0.79977848 0.62806426
  0.19914996 0.7633709  0.30501696 0.97485061 0.15070879 0.57016103
  0.03926901 0.4526602  0.42110316 0.70697413 0.61768404 0.45906735]]
0.4745804194984801


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

#z = np.zeros((10,10))
# for i in range(len(z)):
#   for j in range(len(z)):
#     if(i==0 or i == 9):
#       z[i][j] = 1
#     elif((j==0 or j==9)):
#       z[i][j] = 1
# print(z)
# my function for this 
  



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
z = np.ones((10,10))
z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(z)


# Using fancy indexing
# Z[:, [0, -1]] = 0
# Z[[0, -1], :] = 0
# print(Z)

#another method

# z = np.ones((10,10))
# p = np.zeros((12,12))
# p[1:-1,1:-1] = 1
# z = p
# print(z)
# this is my method to do it can also do it in longer method but ye bhi theek hai

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [91]:
# z = np.zeros((5,5))
# for i in range(len(z)):
#   for j in range (len(z)):
#     if(i == j+1):
#       z[i][j] = int(i)
# print(z)

# the above one is my method but there is one key difference in my solution and the given solution my values are float type while in soltuion they dont have dots so i think it is int type 

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
# z = np.zeros((8,8))
# print(z)
# print(len(z[1]))
# for i in range(len(z)):
#   for j in range(len(z)):
#     if((i%2 ==0) & (j%2 ==0)):
#       z[i][j] = 1
#     elif((i%2 != 0) & (j%2 != 0)):
#       z[i][j] = 1
# print(z)

# this is my code for chess board pattern


Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1 # these all are just fancy indexing
Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [119]:
print(np.unravel_index(99,(6,7,8))) # unravel can be a useful tool in future

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [120]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [132]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.02319469  1.25076741 -1.19049648 -1.22484356  0.65654622]
 [ 0.07417367  1.26837111  0.29550079  1.2237202   0.08491376]
 [ 1.32136696 -0.55880397 -1.72899438 -0.28661187 -0.17652278]
 [-1.20818158  1.14802775  1.01526527 -1.07321873 -1.50153088]
 [ 1.05106686  0.0478306  -0.29489317 -1.39029306  1.17364513]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [134]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [163]:
z1 = np.ones((5,3))
z2 = np.ones((3,2))
print(np.dot(z1,z2))

# other method
# Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
# print(Z)

# logic way


# def dot(a,b):
#   sum = 0
#   for i in range(len(a)):
#     sum += a[i]*b[i]
#   return sum

# dot(z1[0],z2.T[0])

# mut = []
# for i in z1:
#   new = []
#   for j in z2.T:
#     new.append(dot(i,j))
  
#   mut.append(new)
# print(np.array(mut))
    



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(2,22)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # gives sum from 0 to 5-1;
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [181]:
#print(Z**Z) not allowed
print(2 << Z >> 2)
print('hello')
print(Z <- Z)
print('hello')
print(1j*Z)
print('hello')

print(Z/1/1)
#print(Z<Z>Z) not allwoed

[      2       4       0       0       0       0     128     256     512
    1024    2048    4096    8192   16384   32768   65536  131072  262144
  524288 1048576]
hello
[False False  True  True  True  True False False False False False False
 False False False False False False False False]
hello
[ 0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j  0. +8.j  0. +9.j
  0.+10.j  0.+11.j  0.+12.j  0.+13.j  0.+14.j  0.+15.j  0.+16.j  0.+17.j
  0.+18.j  0.+19.j  0.+20.j  0.+21.j]
hello
[ 2.  3. -4. -5. -6. -7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20. 21.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [195]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\binda\AppData\Local\Temp\ipykernel_28344\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\binda\AppData\Local\Temp\ipykernel_28344\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\binda\AppData\Local\Temp\ipykernel_28344\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [196]:

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-5.  2. -4.  8. -2.  8.  8.  9. -2. -2.]
[-5.  2. -4.  8. -2.  8.  8.  9. -2. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [203]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)



print(np.intersect1d(Z1,Z2))

# its logic is also easy so i am not doing that

[1 5 6 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [204]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [206]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # numpy sucks man what the fuck is the difference between two /

False


C:\Users\binda\AppData\Local\Temp\ipykernel_28344\2300188951.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # numpy sucks man what the fuck is the difference between two /


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)